"""Add comment reaction table

Revision ID: 1f32hg89fhrp
Revises: 48a36ae7eab0
Create Date: 2025-02-15 23:41:00.009488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f32hg89fhrp'
down_revision = '48a36ae7eab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'commentreaction',
        sa.Column('id',sa.Integer()),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_id',sa.Integer(),nullable=False),
        sa.Column('reaction_type', sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='comments_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentreaction')
    # ### end Alembic commands ###
