"""Изначальная база данных

Revision ID: 4b34c12fe24e
Revises: 
Create Date: 2025-01-27 18:08:13.207820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b34c12fe24e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
